title: "Cyan's PhD Log"
description: "Research logs, paper notes, and scientific writing practice."

baseurl: "/kit-phd-log"
url: "https://cyans-science.github.io/kit-phd-log/"

markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/

defaults:
  - scope:
      path: "_posts/logs"
      type: "posts"
    values:
      layout: "post"
      category: "logs"

  - scope:
      path: "_posts/papers"
      type: "posts"
    values:
      layout: "post"
      category: "papers"

  - scope:
      path: "_posts/rewrites"
      type: "posts"
    values:
      layout: "post"
      category: "rewrites"